#!/bin/bash

DIR=`dirname $0`

usage() {
    echo "Usage:"
    echo "$0 -t <VELOCITY_TEMPLATE> -m (prop|xml) -f <INPUT_FILE>"
}

while getopts ":ht:m:f:" OPT;
do
    case $OPT in
        h)
            usage
            exit 0
            ;;
        t)
            TEMPLATE=$OPTARG
            ;;
        m)
            INPUT_FORMAT=$OPTARG
            ;;
        f)
            INPUT_FILE=$OPTARG
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -z "$TEMPLATE" ]; then
    echo "VELOCITY_TEMPLATE is required." >& 2
    echo "Try '$0 -h' for more information."
    usage
    exit 1
fi

if [ -z "$INPUT_FORMAT" ]; then
    echo "INPUT_FORMAT is required." >& 2
    echo "Try '$0 -h' for more information."
    usage
    exit 1
fi

if [ -z "$INPUT_FILE" ]; then
    INPUT_FILE="-"
fi

java -jar $DIR/../lib/velocli-jar-with-dependencies.jar $TEMPLATE $INPUT_FORMAT $INPUT_FILE
