#!/bin/bash

DIR=`dirname $0`

usage() {
    echo "Usage:"
    echo "$0 -t <VELOCITY_TEMPLATE> -f (prop|xml) -p <INPUT_PATH>"
}

while getopts ":ht:f:p:" OPT;
do
    case $OPT in
        h)
            usage
            exit 0
            ;;
        t)
            TEMPLATE=$OPTARG
            ;;
        f)
            INPUT_FORMAT=$OPTARG
            ;;
        p)
            INPUT_PATH=$OPTARG
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -z "$TEMPLATE" ]; then
    echo "VELOCITY_TEMPLATE is required." >& 2
    echo "Try '$0 -h' for more information."
    usage
    exit 1
fi

if [ -z "$INPUT_FORMAT" ]; then
    echo "INPUT_FORMAT is required." >& 2
    echo "Try '$0 -h' for more information."
    usage
    exit 1
fi

if [ -z "$INPUT_PATH" ]; then
    INPUT_PATH="-"
fi

java -jar $DIR/../lib/velocli-jar-with-dependencies.jar $TEMPLATE $INPUT_FORMAT $INPUT_PATH
